export const templateBooks = [
  { id: 'quran-sunnah', name: 'Quran & Sunnah', icon: '📖' },
  { id: 'secular', name: 'Atomic / Modern', icon: '📚' },
  { id: 'business', name: 'Business & Agency', icon: '💼' },
  { id: 'mind-body', name: 'Mind & Body', icon: '🧠' },
]

export const habitTemplates = [
  // --- Quran & Sunnah ---
  { name: 'Tahajjud Prayer', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Read 1 Juz of Quran', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Morning Adhkar', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Evening Adhkar', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Duha (Ishraq) Prayer', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Pray on Time (Fajr)', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Pray on Time (Dhuhr)', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Pray on Time (Asr)', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Pray on Time (Maghrib)', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Pray on Time (Isha)', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Read Quran Translation', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Memorize 1 Ayah', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Revise Quran Memorization', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Make Dua List', category: 'Faith', frequency: 'weekly', book: 'quran-sunnah' },
  { name: 'Give Sadaqah', category: 'Faith', frequency: 'weekly', book: 'quran-sunnah' },
  { name: 'Attend Jumuah Early', category: 'Faith', frequency: 'weekly', book: 'quran-sunnah' },
  { name: 'Fast Sunnah (Mon/Thu)', category: 'Faith', frequency: 'weekly', book: 'quran-sunnah' },
  { name: 'Read Hadith (Riyad al-Salihin)', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Dhikr (100x SubhanAllah)', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Dhikr (100x Alhamdulillah)', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Dhikr (100x Allahu Akbar)', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Istighfar (100x Astaghfirullah)', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Salawat on Prophet ﷺ (100x)', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Reflect on 1 Name of Allah', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Tadabbur (Quran Reflection)', category: 'Faith', frequency: 'daily', book: 'quran-sunnah' },
  { name: 'Attend Islamic Circle/Halaqa', category: 'Faith', frequency: 'weekly', book: 'quran-sunnah' },

  // --- Mind & Body ---
  { name: 'Wake Up at 5 AM', category: 'Health', frequency: 'daily', book: 'mind-body' },
  { name: 'Cold Shower (2 min)', category: 'Health', frequency: 'daily', book: 'mind-body' },
  { name: 'Morning Workout (30 min)', category: 'Health', frequency: 'daily', book: 'mind-body' },
  { name: 'Evening Walk', category: 'Health', frequency: 'daily', book: 'mind-body' },
  { name: 'Drink 8 Glasses of Water', category: 'Health', frequency: 'daily', book: 'mind-body' },
  { name: 'Read 10 Pages of a Book', category: 'Learning', frequency: 'daily', book: 'mind-body' },
  { name: 'Journal (3 Things Grateful For)', category: 'Mental', frequency: 'daily', book: 'mind-body' },
  { name: 'No Phone First 30 Min', category: 'Productivity', frequency: 'daily', book: 'mind-body' },
  { name: 'Digital Sunset (No Screens 1h Before Bed)', category: 'Health', frequency: 'daily', book: 'mind-body' },
  { name: 'Meditation (5 min)', category: 'Mental', frequency: 'daily', book: 'mind-body' },
  { name: 'Stretch (10 min)', category: 'Health', frequency: 'daily', book: 'mind-body' },
  { name: 'Limit Caffeine After 3 PM', category: 'Health', frequency: 'daily', book: 'mind-body' },
  { name: 'Sleep by 10 PM', category: 'Health', frequency: 'daily', book: 'mind-body' },
  { name: 'No Sugar Day', category: 'Health', frequency: 'weekly', book: 'mind-body' },
  { name: 'Meal Prep Sunday', category: 'Health', frequency: 'weekly', book: 'mind-body' },
  { name: 'Deep Work Session (90 min)', category: 'Productivity', frequency: 'daily', book: 'mind-body' },
  { name: 'Listen to Podcast (15 min)', category: 'Learning', frequency: 'daily', book: 'mind-body' },

  // --- Business & Agency ---
  { name: 'Call 10 Prospects', category: 'Business', frequency: 'daily', book: 'business' },
  { name: 'Send 5 Follow-Up Messages', category: 'Business', frequency: 'daily', book: 'business' },
  { name: 'Review Pipeline', category: 'Business', frequency: 'daily', book: 'business' },
  { name: 'Post on Social Media', category: 'Business', frequency: 'daily', book: 'business' },
  { name: 'Content Creation (1 piece)', category: 'Business', frequency: 'daily', book: 'business' },
  { name: 'Learn 1 New HVAC Term', category: 'Business', frequency: 'daily', book: 'business' },
  { name: 'Update CRM Records', category: 'Business', frequency: 'daily', book: 'business' },
  { name: 'Review Weekly KPIs', category: 'Business', frequency: 'weekly', book: 'business' },
  { name: 'Client Outreach (3 DMs)', category: 'Business', frequency: 'daily', book: 'business' },
  { name: 'Read Industry News', category: 'Business', frequency: 'daily', book: 'business' },
  { name: 'Skill Practice (30 min)', category: 'Business', frequency: 'daily', book: 'business' },
  { name: 'Network (1 Connection)', category: 'Business', frequency: 'daily', book: 'business' },
  { name: 'Review Ads Performance', category: 'Business', frequency: 'weekly', book: 'business' },
  { name: 'Check Analytics Dashboard', category: 'Business', frequency: 'daily', book: 'business' },
  { name: 'Send Invoice / Follow Payment', category: 'Business', frequency: 'weekly', book: 'business' },

  // --- Atomic / Modern Habits ---
  { name: 'Make Bed', category: 'Productivity', frequency: 'daily', book: 'secular' },
  { name: 'Plan Top 3 Priorities', category: 'Productivity', frequency: 'daily', book: 'secular' },
  { name: 'Evening Reflection (3 Wins)', category: 'Mental', frequency: 'daily', book: 'secular' },
  { name: 'Read 1 Article', category: 'Learning', frequency: 'daily', book: 'secular' },
  { name: 'Write 200 Words', category: 'Learning', frequency: 'daily', book: 'secular' },
  { name: 'Declutter Desk', category: 'Productivity', frequency: 'daily', book: 'secular' },
  { name: 'Review Calendar for Tomorrow', category: 'Productivity', frequency: 'daily', book: 'secular' },
  { name: 'Check Bank Balance', category: 'Finance', frequency: 'daily', book: 'secular' },
  { name: 'Track Expenses', category: 'Finance', frequency: 'daily', book: 'secular' },
  { name: 'No Spend Day', category: 'Finance', frequency: 'weekly', book: 'secular' },
  { name: 'Review Monthly Budget', category: 'Finance', frequency: 'monthly', book: 'secular' },
  { name: 'Call Family Member', category: 'Relationships', frequency: 'weekly', book: 'secular' },
  { name: 'Send Meaningful Text to Friend', category: 'Relationships', frequency: 'daily', book: 'secular' },
  { name: 'Compliment Someone', category: 'Relationships', frequency: 'daily', book: 'secular' },
  { name: 'Practice Gratitude (3 Things)', category: 'Mental', frequency: 'daily', book: 'secular' },
  { name: 'Digital Detox Hour', category: 'Mental', frequency: 'daily', book: 'secular' },
  { name: 'Review Long-Term Goals', category: 'Productivity', frequency: 'weekly', book: 'secular' },
  { name: 'Learn 5 New Words (Language)', category: 'Learning', frequency: 'daily', book: 'secular' },
  { name: 'Practice Instrument (15 min)', category: 'Learning', frequency: 'daily', book: 'secular' },
  { name: 'Write in Journal', category: 'Mental', frequency: 'daily', book: 'secular' },
]

export const categoryColors = {
  Faith: '#34C759',
  Health: '#FF3B30',
  Mental: '#AF52DE',
  Learning: '#5B5BD6',
  Productivity: '#FF9F0A',
  Business: '#FF6482',
  Finance: '#34C759',
  Relationships: '#FF9F0A',
}

export const categoryIcons = {
  Faith: '🕌',
  Health: '💪',
  Mental: '🧠',
  Learning: '📖',
  Productivity: '⚡',
  Business: '💼',
  Finance: '💰',
  Relationships: '💛',
}
