const en = {
  nav: { dashboard: 'Dashboard', schedule: 'Schedule', tasks: 'Tasks', journal: 'Journal', prayers: 'Prayer Tracker', habits: 'Habits', agency: 'Agency', reports: 'Reports', knowledge: 'Knowledge', finance: 'Finance', goals: 'Goals', settings: 'Settings', reading: 'Reading' },
  dashboard: { greeting_morning: 'Good morning', greeting_afternoon: 'Good afternoon', greeting_evening: 'Good evening', greeting_night: 'Good night', tasks_done_today: 'Tasks done today', habits_checked: 'Habits checked', week_completion: 'Week completion', days_building: 'days building', daily_briefing: 'AI Daily Briefing', top_priority: 'Top Priority', quick_check: 'Quick Check', prayer_times: 'Prayer Times', todays_events: "Today's Events", finance: 'Finance', agency_pulse: 'Agency Pulse', latest_journal: 'Latest Journal', daily_review: 'Daily Review', trends_30d: '30-Day Trends', tasks_completed: 'Tasks Completed', habits_done: 'Habits Done', prayer_consistency: 'Prayer Consistency (7d)' },
  goals: { title: 'Goals', new_goal: 'New Goal', total: 'Total', active: 'Active', completed: 'Completed', avg_progress: 'Avg Progress', steps: 'Steps', no_steps_yet: 'No steps yet', add_step: 'Add step...', link_habit: 'Link Habit', ai_coach: 'AI Coach', coach: 'Coach', close: 'Close' },
  habits: { title: 'Habits', new_habit: 'New Habit', day: 'Day', week: 'Week', month: 'Month', streaks: 'Streaks', no_habits: 'No habits yet', streak_leaderboard: 'Streak Leaderboard', current_streaks: 'Current streaks' },
  tasks: { title: 'Tasks', new_task: 'New Task', urgent: 'Urgent', business: 'Business', personal: 'Personal', high: 'High', medium: 'Medium', low: 'Low', todo: 'To Do', in_progress: 'In Progress', done: 'Done', search_placeholder: 'Search tasks...' },
  journal: { title: 'Journal', new_entry: 'New Entry', mood: 'Mood', what_happened: 'What happened?', gratitude: 'Gratitude', muhasaba: 'Self-accounting', tomorrow_intention: "Tomorrow's intention" },
  prayers: { title: 'Prayer Tracker', fajr: 'Fajr', dhuhr: 'Dhuhr', asr: 'Asr', maghrib: 'Maghrib', isha: 'Isha', done: 'Done', missed: 'Missed', streak: 'Streak' },
  settings: { title: 'Settings', general: 'General', ai_assistant: 'AI Assistant', voice_lang: 'Voice Input Language', keyboard_shortcuts: 'Keyboard Shortcuts', backup_restore: 'Backup & Restore', export_data: 'Export Data', import_data: 'Import Data', appearance: 'Appearance', language: 'Language', notifications: 'Notifications' },
  common: { save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', loading: 'Loading...', no_data: 'No data', search: 'Search', close: 'Close', back: 'Back', next: 'Next', done: 'Done', today: 'Today', this_week: 'This Week', this_month: 'This Month', all: 'All', none: 'None' },
}

const ar = {
  nav: { dashboard: 'لوحة التحكم', schedule: 'الجدول', tasks: 'المهام', journal: 'اليوميات', prayers: 'تتبع الصلاة', habits: 'العادات', agency: 'الوكالة', reports: 'التقارير', knowledge: 'المعرفة', finance: 'المالية', goals: 'الأهداف', settings: 'الإعدادات', reading: 'القراءة' },
  dashboard: { greeting_morning: 'صباح الخير', greeting_afternoon: 'مساء الخير', greeting_evening: 'مساء الخير', greeting_night: 'تصبح على خير', tasks_done_today: 'المهام المنجزة اليوم', habits_checked: 'العادات المنجزة', week_completion: 'إنجاز الأسبوع', days_building: 'يوم من البناء', daily_briefing: 'الإحاطة اليومية', top_priority: 'الأولوية القصوى', quick_check: 'فحص سريع', prayer_times: 'أوقات الصلاة', todays_events: 'أحداث اليوم', finance: 'المالية', agency_pulse: 'نبض الوكالة', latest_journal: 'آخر يومية', daily_review: 'المراجعة اليومية', trends_30d: 'اتجاهات 30 يوم', tasks_completed: 'المهام المنجزة', habits_done: 'العادات المنجزة', prayer_consistency: 'ثبات الصلاة (7 أيام)' },
  goals: { title: 'الأهداف', new_goal: 'هدف جديد', total: 'المجموع', active: 'النشط', completed: 'المكتمل', avg_progress: 'متوسط التقدم', steps: 'الخطوات', no_steps_yet: 'لا توجد خطوات بعد', add_step: 'أضف خطوة...', link_habit: 'ربط عادة', ai_coach: 'المدرب الذكي', coach: 'مدرب', close: 'إغلاق' },
  habits: { title: 'العادات', new_habit: 'عادة جديدة', day: 'يوم', week: 'أسبوع', month: 'شهر', streaks: 'التسلسلات', no_habits: 'لا توجد عادات بعد', streak_leaderboard: 'لوحة التسلسلات', current_streaks: 'التسلسلات الحالية' },
  tasks: { title: 'المهام', new_task: 'مهمة جديدة', urgent: 'عاجل', business: 'عمل', personal: 'شخصي', high: 'عالية', medium: 'متوسطة', low: 'منخفضة', todo: 'للقيام', in_progress: 'قيد التنفيذ', done: 'منجز', search_placeholder: 'ابحث عن مهام...' },
  journal: { title: 'اليوميات', new_entry: 'مدخلة جديدة', mood: 'المزاج', what_happened: 'ماذا حدث؟', gratitude: 'امتنان', muhasaba: 'محاسبة النفس', tomorrow_intention: 'نية الغد' },
  prayers: { title: 'تتبع الصلاة', fajr: 'الفجر', dhuhr: 'الظهر', asr: 'العصر', maghrib: 'المغرب', isha: 'العشاء', done: 'أديت', missed: 'فاتت', streak: 'التسلسل' },
  settings: { title: 'الإعدادات', general: 'عام', ai_assistant: 'المساعد الذكي', voice_lang: 'لغة الإدخال الصوتي', keyboard_shortcuts: 'اختصارات لوحة المفاتيح', backup_restore: 'النسخ الاحتياطي', export_data: 'تصدير البيانات', import_data: 'استيراد البيانات', appearance: 'المظهر', language: 'اللغة', notifications: 'الإشعارات' },
  common: { save: 'حفظ', cancel: 'إلغاء', delete: 'حذف', edit: 'تعديل', loading: 'جار التحميل...', no_data: 'لا توجد بيانات', search: 'بحث', close: 'إغلاق', back: 'رجوع', next: 'التالي', done: 'تم', today: 'اليوم', this_week: 'هذا الأسبوع', this_month: 'هذا الشهر', all: 'الكل', none: 'لا شيء' },
}

export const translations = { en, ar }
export const LOCALES = ['en', 'ar']
export const DEFAULT_LOCALE = 'en'
